### ISSUE TITLE
app page erro - Opps! Something went wrong.

### ISSUE THREAD

**Issue by leandrosouza** [tsuru/tsuru-dashboard#101]
ERROR 2015-09-07 12:28:08,500 base 9369 140435884332800 Internal Server Error: /apps/dashboard/
Traceback (most recent call last):
  File "/home/lsouza/.virtualenvs/tsuru-dash/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lsouza/.virtualenvs/tsuru-dash/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/lsouza/hu/projetos/tsuru-dashboard/auth/views.py", line 33, in dispatch
    request, *args, **kwargs)
  File "/home/lsouza/.virtualenvs/tsuru-dash/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/lsouza/.virtualenvs/tsuru-dash/local/lib/python2.7/site-packages/django/views/generic/base.py", line 158, in get
    context = self.get_context_data(**kwargs)
  File "/home/lsouza/hu/projetos/tsuru-dashboard/apps/views.py", line 230, in get_context_data
    if unit['ID'] == container['ID']:
KeyError: 'ID'

**Comment by andrewsmedina** [comment]
fixed by https://github.com/tsuru/tsuru-dashboard/commit/abb780e2fccf6de1236c155468e12c28fce19b06
